# You can use this docker compose file to pre-seed the solr and blazegraph instances with data
#   usage: docker-compose -f docker-compose.yml -f docker-compose.data.yml <command>

version: '3'

services:
    solr:
        build:
            dockerfile: Dockerfile-data
            args:
                # Change the initial seed data.
                # NOTE: The file must be in the build context directory i.e. ./solr
                # In the zip file, there should be a head directory called hadatac_solr with the solr data inside of it
                - SEED=solr.zip

    blazegraph:
        build:
            dockerfile: Dockerfile-data
            args:
                # Change the initial seed data.
                # NOTE: The file must be in the build context directory i.e. ./blazegraph
                # In the zip file, there should be a file called blazegraph.jnl that contains the database
                - SEED=blazegraph.zip
