version: '3'

services:
    # The primary hadatac web app
    hadatac:
        volumes:
            # Mounts the local app directory to the app directory in the Docker container
            # Any changes made locally automatically show up in the Docker container.
            - ./app:/root/app/app
