version: '3'

services:
    solr:
        # Override production restart value to default
        restart: "no"
        environment:
            - VERBOSE=yes
        # Map the solr admin port to the localhost in dev mode
        ports:
            - "8983:8983"

    blazegraph:
        restart: "no"
        ports:
            - "9999:9999"
